services:
  - type: web
    name: product-creation-frontend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 3000
      - key: NEXT_PUBLIC_API_URL
        value: https://product-creation-backend.onrender.com
    region: oregon